name: Release an apworld
description: Package an apworld, generate a default template and create a new release

on:
  workflow_call:
    inputs:
      ap-version:
        description: The version of archipelago to use. This must match a refspec in the archipelago repository
        required: true
        type: string
      python-version:
        description: The python version to use
        required: true
        type: string
      apworld-path:
        description: The path to the apworld folder or apworld file itself
        required: true
        type: string
      apworld-name:
        description: The name of the apworld. This should only be set if the folder storing your apworld in the repository isn't the same
        type: string
      prerelease:
        description: Optionally marks the release as a pre-release
        required: false
        type: boolean
        default: false

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Create apworld
        id: apworld
        uses: Eijebong/ap-actions/package-apworld@main
        with:
          path: ${{ inputs.apworld-path }}
          apworld-name: ${{ inputs.apworld-name }}

      - uses: actions/upload-artifact@v4
        with:
          name: apworld
          path: ${{ steps.apworld.outputs.apworld }}

  template:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/generate-template@main
        id: template
        with:
          apworld-path: ${{ inputs.apworld-path }}
          apworld-name: ${{ inputs.apworld-name}}
          ap-version: ${{ inputs.ap-version }}
          python-version: ${{ inputs.python-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: template
          path: ${{ steps.template.outputs.template }}

  publish:
    runs-on: ubuntu-latest
    needs: [package, template]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apworld

      - uses: actions/download-artifact@v4
        with:
          name: template

      - uses: ncipollo/release-action@v1
        with:
          artifacts: '*'
          allowUpdates: true
          prerelease: ${{ inputs.prerelease }}
          immutableCreate: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
